"""imp: indexes and event type applied field

Revision ID: 496b5ff1f674
Revises: 9d7434856f9c
Create Date: 2022-05-28 04:15:32.217620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496b5ff1f674'
down_revision = '9d7434856f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyzer_user_name', table_name='analyzer_user')
    op.create_unique_constraint(None, 'analyzer_user', ['name'])
    op.add_column(
        'analyzer_web_event', sa.Column('applied', sa.Boolean(), nullable=True)
    )
    op.drop_index('ix_app_web_config_param', table_name='app_web_config')
    op.create_unique_constraint(None, 'app_web_config', ['param'])
    op.drop_index('ix_attachment_hash_ref', table_name='attachment')
    op.create_unique_constraint(None, 'attachment', ['hash_ref'])
    op.drop_index('ix_media_type_short_name', table_name='media_type')
    op.create_unique_constraint(None, 'media_type', ['short_name'])
    op.drop_index('ix_record_metadata_iref', table_name='record_metadata')
    op.create_unique_constraint(None, 'record_metadata', ['iref'])
    op.drop_constraint(
        'rel_analyzer_post_analyzer_post_c_analyzer_post_comment_id_fkey',
        'rel_analyzer_post_analyzer_post_comment',
        type_='foreignkey',
    )
    op.drop_constraint(
        'rel_analyzer_post_analyzer_post_comment_analyzer_post_id_fkey',
        'rel_analyzer_post_analyzer_post_comment',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        'rel_analyzer_post_analyzer_post_comment',
        'analyzer_post_comment',
        ['analyzer_post_comment_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None,
        'rel_analyzer_post_analyzer_post_comment',
        'analyzer_post',
        ['analyzer_post_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        'rel_analyzer_user_avatar_attachment_attachment_id_fkey',
        'rel_analyzer_user_avatar_attachment',
        type_='foreignkey',
    )
    op.drop_constraint(
        'rel_analyzer_user_avatar_attachment_analyzer_user_id_fkey',
        'rel_analyzer_user_avatar_attachment',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        'rel_analyzer_user_avatar_attachment',
        'attachment',
        ['attachment_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None,
        'rel_analyzer_user_avatar_attachment',
        'analyzer_user',
        ['analyzer_user_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_index('ix_web_event_type_short_name', table_name='web_event_type')
    op.create_unique_constraint(None, 'web_event_type', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_event_type', type_='unique')
    op.create_index(
        'ix_web_event_type_short_name', 'web_event_type', ['short_name'], unique=False
    )
    op.drop_constraint(None, 'rel_analyzer_user_avatar_attachment', type_='foreignkey')
    op.drop_constraint(None, 'rel_analyzer_user_avatar_attachment', type_='foreignkey')
    op.create_foreign_key(
        'rel_analyzer_user_avatar_attachment_analyzer_user_id_fkey',
        'rel_analyzer_user_avatar_attachment',
        'analyzer_user',
        ['analyzer_user_id'],
        ['id'],
    )
    op.create_foreign_key(
        'rel_analyzer_user_avatar_attachment_attachment_id_fkey',
        'rel_analyzer_user_avatar_attachment',
        'attachment',
        ['attachment_id'],
        ['id'],
    )
    op.drop_constraint(
        None, 'rel_analyzer_post_analyzer_post_comment', type_='foreignkey'
    )
    op.drop_constraint(
        None, 'rel_analyzer_post_analyzer_post_comment', type_='foreignkey'
    )
    op.create_foreign_key(
        'rel_analyzer_post_analyzer_post_comment_analyzer_post_id_fkey',
        'rel_analyzer_post_analyzer_post_comment',
        'analyzer_post',
        ['analyzer_post_id'],
        ['id'],
    )
    op.create_foreign_key(
        'rel_analyzer_post_analyzer_post_c_analyzer_post_comment_id_fkey',
        'rel_analyzer_post_analyzer_post_comment',
        'analyzer_post_comment',
        ['analyzer_post_comment_id'],
        ['id'],
    )
    op.drop_constraint(None, 'record_metadata', type_='unique')
    op.create_index(
        'ix_record_metadata_iref', 'record_metadata', ['iref'], unique=False
    )
    op.drop_constraint(None, 'media_type', type_='unique')
    op.create_index(
        'ix_media_type_short_name', 'media_type', ['short_name'], unique=False
    )
    op.drop_constraint(None, 'attachment', type_='unique')
    op.create_index('ix_attachment_hash_ref', 'attachment', ['hash_ref'], unique=False)
    op.drop_constraint(None, 'app_web_config', type_='unique')
    op.create_index(
        'ix_app_web_config_param', 'app_web_config', ['param'], unique=False
    )
    op.drop_column('analyzer_web_event', 'applied')
    op.drop_constraint(None, 'analyzer_user', type_='unique')
    op.create_index('ix_analyzer_user_name', 'analyzer_user', ['name'], unique=False)
    # ### end Alembic commands ###
