"""Restore avatar_url field

Revision ID: 50f03b109fef
Revises: 5d9ab6cd8638
Create Date: 2022-04-29 01:42:30.836896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50f03b109fef'
down_revision = '5d9ab6cd8638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'analyzer_user', sa.Column('last_avatar_url', sa.Text(), nullable=True)
    )
    op.alter_column(
        'attachment', 'data', existing_type=postgresql.BYTEA(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'attachment', 'data', existing_type=postgresql.BYTEA(), nullable=True
    )
    op.drop_column('analyzer_user', 'last_avatar_url')
    # ### end Alembic commands ###
