"""imp: create model record_metadata

Revision ID: 9d7434856f9c
Revises: a72aed44445e
Create Date: 2022-05-01 00:03:32.819869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d7434856f9c'
down_revision = 'a72aed44445e'
branch_labels = None
depends_on = None


def _move_iref(session, tablename):
    records = session.execute(
        f'select id, iref from {tablename} where iref is not null'
    )
    for record in records:
        session.execute(
            'insert into record_metadata (iref, object_model, object_id) values (:iref, :object_model, :object_id)',
            {'iref': record[1], 'object_model': tablename, 'object_id': record[0]},
        )


def upgrade():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'record_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'create_date',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True,
        ),
        sa.Column('write_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('iref', sa.String(length=92), nullable=False),
        sa.Column('object_id', sa.Integer(), nullable=False),
        sa.Column('object_model', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_record_metadata_iref'), 'record_metadata', ['iref'], unique=True
    )
    _move_iref(session, 'analyzer_post')
    _move_iref(session, 'analyzer_post_comment')
    _move_iref(session, 'analyzer_post_media')
    _move_iref(session, 'analyzer_post_stat')
    _move_iref(session, 'analyzer_thread')
    _move_iref(session, 'analyzer_thread_category')
    _move_iref(session, 'analyzer_user')
    _move_iref(session, 'analyzer_web_event')
    _move_iref(session, 'app_web_config')
    _move_iref(session, 'attachment')
    _move_iref(session, 'media_type')
    _move_iref(session, 'site')
    _move_iref(session, 'web_event_type')
    op.drop_index('ix_analyzer_post_iref', table_name='analyzer_post')
    op.drop_column('analyzer_post', 'iref')
    op.drop_index('ix_analyzer_post_comment_iref', table_name='analyzer_post_comment')
    op.drop_column('analyzer_post_comment', 'iref')
    op.drop_index('ix_analyzer_post_media_iref', table_name='analyzer_post_media')
    op.drop_column('analyzer_post_media', 'iref')
    op.drop_index('ix_analyzer_post_stat_iref', table_name='analyzer_post_stat')
    op.drop_column('analyzer_post_stat', 'iref')
    op.drop_index('ix_analyzer_thread_iref', table_name='analyzer_thread')
    op.drop_column('analyzer_thread', 'iref')
    op.drop_index(
        'ix_analyzer_thread_category_iref', table_name='analyzer_thread_category'
    )
    op.drop_column('analyzer_thread_category', 'iref')
    op.drop_index('ix_analyzer_user_iref', table_name='analyzer_user')
    op.drop_column('analyzer_user', 'iref')
    op.drop_index('ix_analyzer_web_event_iref', table_name='analyzer_web_event')
    op.drop_column('analyzer_web_event', 'iref')
    op.drop_index('ix_app_web_config_iref', table_name='app_web_config')
    op.drop_column('app_web_config', 'iref')
    op.drop_index('ix_attachment_iref', table_name='attachment')
    op.drop_column('attachment', 'iref')
    op.drop_index('ix_media_type_iref', table_name='media_type')
    op.drop_column('media_type', 'iref')
    op.drop_index('ix_site_iref', table_name='site')
    op.drop_column('site', 'iref')
    op.drop_index('ix_web_event_type_iref', table_name='web_event_type')
    op.drop_column('web_event_type', 'iref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'web_event_type',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_web_event_type_iref', 'web_event_type', ['iref'], unique=False)
    op.add_column(
        'site',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_site_iref', 'site', ['iref'], unique=False)
    op.add_column(
        'media_type',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_media_type_iref', 'media_type', ['iref'], unique=False)
    op.add_column(
        'attachment',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_attachment_iref', 'attachment', ['iref'], unique=False)
    op.add_column(
        'app_web_config',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_app_web_config_iref', 'app_web_config', ['iref'], unique=False)
    op.add_column(
        'analyzer_web_event',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index(
        'ix_analyzer_web_event_iref', 'analyzer_web_event', ['iref'], unique=False
    )
    op.add_column(
        'analyzer_user',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_analyzer_user_iref', 'analyzer_user', ['iref'], unique=False)
    op.add_column(
        'analyzer_thread_category',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index(
        'ix_analyzer_thread_category_iref',
        'analyzer_thread_category',
        ['iref'],
        unique=False,
    )
    op.add_column(
        'analyzer_thread',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index(
        'ix_analyzer_thread_iref', 'analyzer_thread', ['iref'], unique=False
    )
    op.add_column(
        'analyzer_post_stat',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index(
        'ix_analyzer_post_stat_iref', 'analyzer_post_stat', ['iref'], unique=False
    )
    op.add_column(
        'analyzer_post_media',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index(
        'ix_analyzer_post_media_iref', 'analyzer_post_media', ['iref'], unique=False
    )
    op.add_column(
        'analyzer_post_comment',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index(
        'ix_analyzer_post_comment_iref', 'analyzer_post_comment', ['iref'], unique=False
    )
    op.add_column(
        'analyzer_post',
        sa.Column('iref', sa.VARCHAR(length=92), autoincrement=False, nullable=True),
    )
    op.create_index('ix_analyzer_post_iref', 'analyzer_post', ['iref'], unique=False)
    op.drop_table('record_metadata')
    # ### end Alembic commands ###
