"""imp: add iref col

Revision ID: a4ac5c97faa6
Revises: 8e878081ba47
Create Date: 2022-04-30 03:37:18.418551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4ac5c97faa6'
down_revision = '8e878081ba47'
branch_labels = None
depends_on = None


def _set_default_iref(session, tablename):
    session.execute(
        f"update {tablename} set iref = 'model_' || :tablename || '__record_' || id",
        {'tablename': tablename},
    )


def _fix_base_iref(session):
    session.execute(
        f"update site set iref = 'site_mediavida' where iref = 'model_site__record_1'"
    )
    session.execute(
        f"update media_type set iref = 'base_media_type_link' where iref = 'model_media_type__record_1'"
    )
    session.execute(
        f"update media_type set iref = 'base_media_type_youtube' where iref = 'model_media_type__record_2'"
    )
    session.execute(
        f"update media_type set iref = 'base_media_type_soundcloud' where iref = 'model_media_type__record_3'"
    )
    session.execute(
        f"update media_type set iref = 'base_media_type_twitter' where iref = 'model_media_type__record_4'"
    )
    session.execute(
        f"update media_type set iref = 'base_media_type_image' where iref = 'model_media_type__record_5'"
    )
    session.execute(
        f"update web_event_type set iref = 'base_web_event_type_online_users' where iref = 'model_web_event_type__record_1'"
    )
    session.execute(
        f"update web_event_type set iref = 'base_web_event_type_post_reply' where iref = 'model_web_event_type__record_2'"
    )
    session.execute(
        f"update web_event_type set iref = 'base_web_event_type_post_mention' where iref = 'model_web_event_type__record_3'"
    )
    session.execute(
        f"update web_event_type set iref = 'base_web_event_type_user_avatar_change' where iref = 'model_web_event_type__record_4'"
    )
    session.execute(
        f"update web_event_type set iref = 'base_web_event_type_user_banned' where iref = 'model_web_event_type__record_5'"
    )
    session.execute(
        f"update web_event_type set iref = 'base_web_event_type_user_deleted' where iref = 'model_web_event_type__record_6'"
    )


def upgrade():
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'analyzer_post',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_post_comment',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_post_media',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_post_stat',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_thread',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_thread_category',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_user',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'analyzer_web_event',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'app_web_config',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    op.add_column(
        'attachment', sa.Column('iref', sa.String(length=92), unique=True, index=True)
    )
    op.add_column(
        'media_type', sa.Column('iref', sa.String(length=92), unique=True, index=True)
    )
    op.add_column(
        'site', sa.Column('iref', sa.String(length=92), unique=True, index=True)
    )
    op.add_column(
        'web_event_type',
        sa.Column('iref', sa.String(length=92), unique=True, index=True),
    )
    _set_default_iref(session, 'analyzer_post')
    _set_default_iref(session, 'analyzer_post_comment')
    _set_default_iref(session, 'analyzer_post_media')
    _set_default_iref(session, 'analyzer_post_stat')
    _set_default_iref(session, 'analyzer_thread')
    _set_default_iref(session, 'analyzer_thread_category')
    _set_default_iref(session, 'analyzer_user')
    _set_default_iref(session, 'analyzer_web_event')
    _set_default_iref(session, 'app_web_config')
    _set_default_iref(session, 'attachment')
    _set_default_iref(session, 'media_type')
    _set_default_iref(session, 'site')
    _set_default_iref(session, 'web_event_type')
    _fix_base_iref(session)
    op.alter_column('analyzer_post', 'iref', nullable=False)
    op.alter_column('analyzer_post_comment', 'iref', nullable=False)
    op.alter_column('analyzer_post_media', 'iref', nullable=False)
    op.alter_column('analyzer_post_stat', 'iref', nullable=False)
    op.alter_column('analyzer_thread', 'iref', nullable=False)
    op.alter_column('analyzer_thread_category', 'iref', nullable=False)
    op.alter_column('analyzer_user', 'iref', nullable=False)
    op.alter_column('analyzer_web_event', 'iref', nullable=False)
    op.alter_column('app_web_config', 'iref', nullable=False)
    op.alter_column('attachment', 'iref', nullable=False)
    op.alter_column('media_type', 'iref', nullable=False)
    op.alter_column('site', 'iref', nullable=False)
    op.alter_column('web_event_type', 'iref', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('web_event_type', 'iref')
    op.drop_column('site', 'iref')
    op.drop_column('media_type', 'iref')
    op.drop_column('attachment', 'iref')
    op.drop_column('app_web_config', 'iref')
    op.drop_column('analyzer_web_event', 'iref')
    op.drop_column('analyzer_user', 'iref')
    op.drop_column('analyzer_thread_category', 'iref')
    op.drop_column('analyzer_thread', 'iref')
    op.drop_column('analyzer_post_stat', 'iref')
    op.drop_column('analyzer_post_media', 'iref')
    op.drop_column('analyzer_post_comment', 'iref')
    op.drop_column('analyzer_post', 'iref')
    # ### end Alembic commands ###
