"""imp: analyzer web event

Revision ID: c5454911444d
Revises: 496b5ff1f674
Create Date: 2022-05-29 00:21:07.877000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5454911444d'
down_revision = '496b5ff1f674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'analyzer_post_site_id_fkey', 'analyzer_post', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'analyzer_post', 'site', ['site_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint(
        'analyzer_thread_site_id_fkey', 'analyzer_thread', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'analyzer_thread', 'site', ['site_id'], ['id'], ondelete='CASCADE'
    )
    op.drop_constraint(
        'analyzer_thread_category_site_id_fkey',
        'analyzer_thread_category',
        type_='foreignkey',
    )
    op.create_foreign_key(
        None,
        'analyzer_thread_category',
        'site',
        ['site_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint(
        'analyzer_user_site_id_fkey', 'analyzer_user', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'analyzer_user', 'site', ['site_id'], ['id'], ondelete='CASCADE'
    )
    op.add_column(
        'analyzer_web_event', sa.Column('thread_id', sa.Integer(), nullable=True)
    )
    op.add_column(
        'analyzer_web_event', sa.Column('diff_count', sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        'analyzer_web_event_site_id_fkey', 'analyzer_web_event', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'analyzer_web_event', 'analyzer_thread', ['thread_id'], ['id']
    )
    op.create_foreign_key(
        None, 'analyzer_web_event', 'site', ['site_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyzer_web_event', type_='foreignkey')
    op.drop_constraint(None, 'analyzer_web_event', type_='foreignkey')
    op.create_foreign_key(
        'analyzer_web_event_site_id_fkey',
        'analyzer_web_event',
        'site',
        ['site_id'],
        ['id'],
    )
    op.drop_column('analyzer_web_event', 'diff_count')
    op.drop_column('analyzer_web_event', 'thread_id')
    op.drop_constraint(None, 'analyzer_user', type_='foreignkey')
    op.create_foreign_key(
        'analyzer_user_site_id_fkey', 'analyzer_user', 'site', ['site_id'], ['id']
    )
    op.drop_constraint(None, 'analyzer_thread_category', type_='foreignkey')
    op.create_foreign_key(
        'analyzer_thread_category_site_id_fkey',
        'analyzer_thread_category',
        'site',
        ['site_id'],
        ['id'],
    )
    op.drop_constraint(None, 'analyzer_thread', type_='foreignkey')
    op.create_foreign_key(
        'analyzer_thread_site_id_fkey', 'analyzer_thread', 'site', ['site_id'], ['id']
    )
    op.drop_constraint(None, 'analyzer_post', type_='foreignkey')
    op.create_foreign_key(
        'analyzer_post_site_id_fkey', 'analyzer_post', 'site', ['site_id'], ['id']
    )
    # ### end Alembic commands ###
